# workflow to test AWS OIDC access
name: test github aws sts assume

on:
  # Show manual 'Run workflow button'
  workflow_dispatch:

env:
  AWS_REGION: "eu-west-2" # Change to reflect your Region

permissions:
  id-token: write # Required for fetching an OIDC token.
  contents: read # Required for actions/checkout.
  pull-requests: write # Required to post plan to PR comment.

jobs:
  AssumeRoleAndCallIdentity:
    name: aws-assume-role
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout 🔄
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      # AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
