name: matrix terraform apply

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: The GitHub environment being deployed to
        required: false
        type: string
      REGION:
        description: Region to run job as (prefix only - e.g eu-north-1, eu-west-2)
        type: string
        required: true
      CONFIG_FOLDER_PATH:
        description: The base path of the Terraform config you are wanting to plan
        type: string
        required: true

permissions:
  id-token: write # Required for fetching an OIDC token.
  contents: read # Required for actions/checkout.
  pull-requests: write # Required to post plan to PR comment.

env:
  AWS_REGION: ${{ inputs.REGION }}

jobs:
  terraform-apply:
    name: terraform-apply
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout 🔄
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform 🛠️
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          # This needs to be true to get stdout and std error from the tf-plan step
          # https://github.com/marketplace/actions/hashicorp-setup-terraform#outputs
          terraform_wrapper: true

      - name: Terraform Init 🔧
        run: terraform -chdir=${{ inputs.CONFIG_FOLDER_PATH }} init -backend-config=./backend/${{ inputs.REGION }}.cfg

      # Apply terraform and deploy resources
      - name: Terraform Apply
        id: plan
        run: |
          terraform -chdir=${{ inputs.CONFIG_FOLDER_PATH }} apply -input=false -auto-approve -var-file=./tfvars/common.tfvars -var-file=./tfvars/${{ inputs.REGION }}.tfvars
        continue-on-error: false
