name: eu-north-1 apply

on:
  # Show manual 'Run workflow button'
  workflow_dispatch:
  # Run on pull request for main branch
  #pull_request:
  #  types: [opened, synchronize, reopened]
  #  branches:
  #  - 'main'

permissions:
  id-token: write # Required for fetching an OIDC token.
  contents: read # Required for actions/checkout.
  pull-requests: write # Required to post plan to PR comment.

jobs:
  terraform-apply:
    strategy:
      fail-fast: false
    uses: ./.github/workflows/ci-matrix-terraform-apply.yaml
    with:
      CONFIG_FOLDER_PATH: .
      REGION: eu-north-1
    secrets: inherit
